### ISSUE TITLE
Cannot find module 'sharp' during runtime

### ISSUE THREAD

**Issue by anishagg17** [ryands17/s3-thumbnail-generator#93]
@ryands17 whenever I make a deployment following the steps within the `Readme.md`, and then add an object to the `S3` bucket with `photos` prefix, nothing happens and when I try to invoke it using lambda, it renders this error.

```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'sharp'\nRequire stack:\n- /var/task/function.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'sharp'",
    "Require stack:",
    "- /var/task/function.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
    "    at Module.load (internal/modules/cjs/loader.js:863:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}
```

**Comment by ryands17** [comment]
@anishagg17 👋 
Updated the `README.md` for installation instructions :)
